<a href="https://colab.research.google.com/github/iCarlosCarhuas/direct-wi-fi-acces-using-cellphone-bluetooth/blob/main/Iris_Clasification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
#Import Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [86]:
#Loading Dataset
img = datasets.load_sample_image(image_name=(""))
print(img)

[[[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [250 251 255]
  [250 251 255]
  [250 251 255]]

 [[172 199 229]
  [173 200 230]
  [173 200 230]
  ...
  [251 252 255]
  [251 252 255]
  [251 252 255]]

 [[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [252 253 255]
  [252 253 255]
  [252 253 255]]

 ...

 [[ 88  80   7]
  [147 138  69]
  [122 116  38]
  ...
  [ 39  42  33]
  [  8  14   2]
  [  6  12   0]]

 [[122 112  41]
  [129 120  53]
  [118 112  36]
  ...
  [  9  12   3]
  [  9  15   3]
  [ 16  24   9]]

 [[116 103  35]
  [104  93  31]
  [108 102  28]
  ...
  [ 43  49  39]
  [ 13  21   6]
  [ 15  24   7]]]


In [80]:
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [81]:
#Split Dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3) 

In [82]:
#Data Shape
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [83]:
# Building the Model
model= Sequential()
model.add(Dense(100, input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [84]:
#Compile the model

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


In [85]:
#Fit the Model
model.fit(x_train,y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 3ms/step - loss: 1.9017 - accuracy: 0.2571
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.5420 - accuracy: 0.2571
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2626 - accuracy: 0.2571
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0998 - accuracy: 0.2667
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9903 - accuracy: 0.5905
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9522 - accuracy: 0.7238
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9273 - accuracy: 0.7143
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8985 - accuracy: 0.7238
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8613 - accuracy: 0.7333
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8244 - accuracy: 0.7429
Epoch 11/100
4/4 [===========

In [66]:
#Evaluate the Model

model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.1986 - accuracy: 0.9778


[0.19857525825500488, 0.9777777791023254]

In [68]:
#Predict for the first 10 observations
pred=model.predict(x_test[:10])
print(pred)

[[7.5754884e-04 1.8414029e-01 8.1510222e-01]
 [1.3028828e-02 7.1336591e-01 2.7360529e-01]
 [1.8200916e-03 2.9027778e-01 7.0790207e-01]
 [9.8300964e-01 1.6919108e-02 7.1222661e-05]
 [9.9345136e-01 6.5357429e-03 1.2947060e-05]
 [4.2158023e-02 8.2890105e-01 1.2894088e-01]
 [9.7010648e-01 2.9711850e-02 1.8166179e-04]
 [6.7726884e-04 2.1211223e-01 7.8721052e-01]
 [2.2182241e-02 8.4925878e-01 1.2855899e-01]
 [9.6469760e-01 3.5057016e-02 2.4541860e-04]]


In [69]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 1 2 0 0 1 0 2 1 0]
[2 1 1 0 0 1 0 2 1 0]


In [70]:
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
